{ -*- buffer-read-only: t -*- }

{ Unit automatically generated by image-to-pascal tool,
  to embed images in Pascal source code.
  @exclude (Exclude this unit from PasDoc documentation.) }
unit decoloadembedded;

interface

uses CastleImages;

var
  Loading_image: TGrayscaleImage;

implementation

uses SysUtils;

{ Actual image data is included from another file, with a deliberately
  non-Pascal file extension ".image_data". This way online code analysis
  tools will NOT consider this source code as an uncommented Pascal code
  (which would be unfair --- the image data file is autogenerated
  and never supposed to be processed by a human). }
{$I decoloadembedded.image_data}

initialization
  Loading_image := TGrayscaleImage.Create(Loading_imageWidth, Loading_imageHeight, Loading_imageDepth);
  Move(Loading_imagePixels, Loading_image.RawPixels^, SizeOf(Loading_imagePixels));
  Loading_image.URL := 'embedded-image:/Loading_image';
finalization
  FreeAndNil(Loading_image);
end.